### ISSUE TITLE
It seems like dynamic string slicing is not allowed in ExpressionTransformer

### ISSUE THREAD

**Issue by leonardosavasta** [jpmml/jpmml-python#18] opened 2022-06-03 14:35 UTC
Hello Villu,

Not sure if this is an issue per se, but it seems like following statement is not allowed for PMML conversion:
```python
ExpressionTransformer("X[1][0:X[0]]") - Where X[1] is a string and X[0] is an integer I want to use to slice X[1].
```

Is there any way to achieve this with the current functionality? I have tested different options and they all seem to not work for one reason or another.

The expression works fine when testing in Python, however, when using sklearn2pmml.sklearn2pmml it throws an error. Please find an example of the code:

```python
prep_pipe = pipeline.Pipeline([
    # Previous transformations
    , ("trim_string", proc.ExpressionTransformer("X[1][0:X[0]]"))
    ])

fitted_pipe = prep_pipe.fit(df[column_list])
fitted_pipe_pmml = sklearn2pmml.make_pmml_pipeline(fitted_pipe)
sklearn2pmml.sklearn2pmml(fitted_pipe_pmml, path)
```

This gives the following error:

```
Exception in thread "main" java.lang.IllegalArgumentException: Python expression 'X[1][0:X[0]]' is either invalid or not supported
	at org.jpmml.python.ExpressionTranslator.translate(ExpressionTranslator.java:35)
	at org.jpmml.python.ExpressionTranslator.translate(ExpressionTranslator.java:22)
	at sklearn2pmml.preprocessing.ExpressionTransformer.encodeFeatures(ExpressionTransformer.java:73)
	at sklearn.Transformer.encode(Transformer.java:69)
	at sklearn.Composite.encodeFeatures(Composite.java:119)
	at sklearn2pmml.pipeline.PMMLPipeline.encodePMML(PMMLPipeline.java:212)
	at com.sklearn2pmml.Main.run(Main.java:84)
	at com.sklearn2pmml.Main.main(Main.java:62)
Caused by: org.jpmml.python.ParseException: Encountered unexpected token: "X" <NAME>
    at line 1, column 8.

Was expecting one of:

    "+"
    "-"
    "]"
    <INT>

	at org.jpmml.python.ExpressionTranslator.generateParseException(ExpressionTranslator.java:2152)
	at org.jpmml.python.ExpressionTranslator.jj_consume_token(ExpressionTranslator.java:2015)
	at org.jpmml.python.ExpressionTranslator.StringSlicingExpression(ExpressionTranslator.java:958)
	at org.jpmml.python.ExpressionTranslator.PrimaryExpression(ExpressionTranslator.java:628)
	at org.jpmml.python.ExpressionTranslator.UnaryExpression(ExpressionTranslator.java:588)
	at org.jpmml.python.ExpressionTranslator.MultiplicativeExpression(ExpressionTranslator.java:529)
	at org.jpmml.python.ExpressionTranslator.AdditiveExpression(ExpressionTranslator.java:485)
	at org.jpmml.python.ExpressionTranslator.ComparisonExpression(ExpressionTranslator.java:425)
	at org.jpmml.python.ExpressionTranslator.NegationExpression(ExpressionTranslator.java:380)
	at org.jpmml.python.ExpressionTranslator.LogicalAndExpression(ExpressionTranslator.java:350)
	at org.jpmml.python.ExpressionTranslator.LogicalOrExpression(ExpressionTranslator.java:329)
	at org.jpmml.python.ExpressionTranslator.IfElseExpression(ExpressionTranslator.java:310)
	at org.jpmml.python.ExpressionTranslator.Expression(ExpressionTranslator.java:303)
	at org.jpmml.python.ExpressionTranslator.translateExpressionInternal(ExpressionTranslator.java:297)
	at org.jpmml.python.ExpressionTranslator.translate(ExpressionTranslator.java:33)
7 more
```

Thank you!

**Comment by vruusmann** [comment] 2022-06-03 15:26
> Is there any way to achieve this with the current functionality?

The currently supported syntax for string slicing is defined in JavaCC grammar file:
https://github.com/jpmml/jpmml-python/blob/1.1.5/pmml-python/src/main/javacc/expression.jj#L778-L801

It's basically `[<signed integer>? : <signed integer>?]`

There are no restrictions (from the PMML specification side) why slice bounds couldn't be defined using "nested expressions" instead of plain integer literals.

> Is there any way to achieve this with the current functionality? I have tested different options and they all seem to not work for one reason or another.

This functionality needs JavaCC grammar refactoring.

I can't think of any `ExpressionTransformer`-level workarounds that might work with the existing grammar version - it won't accept anything but integer literals in those places.

> `("trim_string", ExpressionTransformer(...))`

If you're trying to trim whitespace from user input, then you could use the `strip()` Python function instead: `ExpressionTransformer("strip(X[0])")`

**Comment by vruusmann** [comment] 2023-02-20 18:24
Closing as "won't fix" - not worth the effort.

The problem is that Python and PMML use different indexing mechanisms:

- Python: absolute - get characters from `startPos` to `endPos`; 0-indexed.
- PMML: relative - get `length` number of characters starting from `startPos`; 1-indexed.

When given dynamic slice indices, then the main problem is figuring out if they represent positive (start from the beginning) or negative (start from the end) values - many PMML code paths.

With static slice indices, the intended indexing direction is evident at the time of translatio - one PMML code path.

**Closed as completed by vruusmann** 2023-02-20 18:24 UTC
